services:
  knowledgebot:
    image: knowledgebot
    #environment:
    #  KLB_OPENAI_URL: http://ollama:11434
    ports:
      - "8080:8080"
    volumes:
      - "./ui:/var/lib/knowledgebot/ui"
    depends_on:
      - qdrant
      - ollama
      #- localai
  qdrant:
    image: qdrant/qdrant:v1.14.1-unprivileged
    ports:
      - "6333:6333"
    volumes:
      - 'qdrant-data:/qdrant/storage:z'
  ollama:
    image: ollama/ollama:0.9.0
    ports:
      - "11434:11434"
    volumes:
      - 'ollama-data:/root/.ollama'
  #localai:
  #  image: localai/localai:v2.29.0-vulkan
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - 'localai-models:/build/models:z'
  #  privileged: true

volumes:
  qdrant-data:
  ollama-data:
  #localai-models:
